### ISSUE TITLE
有关于效果展示

### ISSUE THREAD

**Issue by tongchangD** [Fanghua-Yu/SUPIR#1]
为何不使用gradio 这种较为类似的搭建一个测试damo以供测试，从提供的几张图示例来看，是比较惊艳的了

**Comment by tongchangD** [comment]
看了论文
`We collect a dataset comprising 20 million highresolution, high-quality images for model training, each enriched with descriptive text annotations.`

请问是否可能只是因为是大批量的训练数据使得模型效果OK  

请问是否直接用这批数据直接训练过其他超分的模型  

请问您的对比是直接拿现有的模型在测试数据集中挑选数据测试的，还是基于您大批量数据训练之后的效果测试对比

**Comment by JasonGUTU** [comment]
我们直接和其他开源的方法进行的对比。我们的目的并不是为了证明我们的架构在学术上具有绝对优势，而是证明底层视觉大模型的潜力。数据是开发大模型不能被忽视的重要一环，这不仅涉及数据的收集，还涉及数据的清洗，处理，加权等。我们不否认其他的方法同样在大量数据上训练之后的可能的效果。但是我们同样也强调我们这个工作的独特价值。模型规模化是一个系统性的工程，并不是数据量上去了，任何一个模型都能成功。否则GPT4也就不再是GPT4了。

我们会后续放出源代码，并开放线上免费测试。欢迎关注尝试，并反馈意见。

**Comment by zdyshine** [comment]
> 我们直接和其他开源的方法进行的对比。我们的目的并不是为了证明我们的架构在学术上具有绝对优势，而是证明底层视觉大模型的潜力。数据是开发大模型不能被忽视的重要一环，这不仅涉及数据的收集，还涉及数据的清洗，处理，加权等。我们不否认其他的方法同样在大量数据上训练之后的可能的效果。但是我们同样也强调我们这个工作的独特价值。模型规模化是一个系统性的工程，并不是数据量上去了，任何一个模型都能成功。否则GPT4也就不再是GPT4了。
> 
> 我们会后续放出源代码，并开放线上免费测试。欢迎关注尝试，并反馈意见。

数据会开源出来吗

**Comment by JasonGUTU** [comment]
数据需要进行合规性检查并安排合适的license。可能不会很快开源。

**Comment by JasonGUTU** [comment]
数据开源问题将在别的issue中讨论。

**Comment by rainsoulsrx** [comment]
> 数据开源问题将在别的issue中讨论。

请问会开源训练代码让我们用自己的数据去finetune开源的模型吗？因为测试下来在一些场景上的表现不太好，比如人像场景，原始图糊的测试图，模型结果还是比较糊，只是有很微弱的提升。

**Comment by JasonGUTU** [comment]
如果您能反映这些failure cases就最好了，我们估计是使用方法导致的问题。可以邮件给我们这些图我们来试一试

**Comment by rainsoulsrx** [comment]
> 如果您能反映这些failure cases就最好了，我们估计是使用方法导致的问题。可以邮件给我们这些图我们来试一试

你好，感谢您的及时回复，我邮件发您了一些图，烦请帮忙看一下。

**Comment by rainsoulsrx** [comment]
> > 如果您能反映这些failure cases就最好了，我们估计是使用方法导致的问题。可以邮件给我们这些图我们来试一试
> 
> 你好，感谢您的及时回复，我邮件发您了一些图，烦请帮忙看一下。

我看到您在其他的问题下面回复说正在把人脸restoration的模块加入进来，所以针对人脸效果不好的问题是已经明确了吗，不是使用方法导致？
那么为什么对于人脸的表现不好呢，是因为数据不足导致的吗？因为我看文章里面也提到专门加入了FFHQ的数据集。

**Comment by tongchangD** [comment]
> 数据需要进行合规性检查并安排合适的license。可能不会很快开源。

我觉得可以打开这个issuse，我们就只是讨论这个模型效果
