### ISSUE TITLE
Some wrong implements

### ISSUE THREAD

**Issue by CuddleSabe** [Fanghua-Yu/SUPIR#103]
hi, I found the code  in LightGLVUNet.forward is wrong
"
_h = hs.pop()
h = self.project_modules[adapter_idx](control[control_idx], _h, h, control_scale=control_scale)
"

the _h is the output of the downsmple, and its the add_res of the upsample

I think it should be "(control[control_idx], h, _h, control_scale=control_scale)",
not the "(control[control_idx], _h, h, control_scale=control_scale)"

**Comment by FurkanGozukara** [comment]
after this change what did you notice what effect did it have @CuddleSabe ?
