### ISSUE TITLE
can you share training code please

### ISSUE THREAD

**Issue by peng25zhang** [Fanghua-Yu/SUPIR#114]

**Comment by aulaywang** [comment]
waiting for training code

**Comment by gitlabspy** [comment]
It should be trained like a normal diffusion/controlnet, in my opinion.

**Comment by Dong1P** [comment]
"If uploading the training code is burdensome, please upload at least the scratch code or the config files."

**Comment by JasonGUTU** [comment]
Thank you for your interest. However, we have no plans to release training code in the short term.
