### ISSUE TITLE
About train code

### ISSUE THREAD

**Issue by c-pupil** [Fanghua-Yu/SUPIR#129]
Hello, are there any plans to release the training  code in the future?
 您好，请问接下来是否都发布训练代码的打算，后面想要在自己的数据集训和基于这个pipeline开展一下其他task的工作。

**Comment by Dong1P** [comment]
If it's difficult to upload the training code, please at least upload the config files...Please!!

**Comment by JasonGUTU** [comment]
Thank you for your interest. However, we have no plans to release training code in the short term.
