### ISSUE TITLE
How to improve the model performance for the text image?

### ISSUE THREAD

**Issue by Wangbk-dl** [Fanghua-Yu/SUPIR#137]
I've tried several images with text. The result is poor that the characters in the image became weird. How to improve that?
![66af3555b959fb61c48200ba](https://github.com/user-attachments/assets/c4befbee-4bfe-4903-9897-477b8f1d47a9)

**Comment by JasonGUTU** [comment]
Can you also share the input image? We need to see whether the information already lost.

**Comment by Wangbk-dl** [comment]
> Can you also share the input image? We need to see whether the information already lost.
Sure, here is the original input image, and the setting is 

Upscale Factor
1
Prioritizing
Fidelity

![88a2aba8-0a63-11ee-aa1c-0a580a22ea3e](https://github.com/user-attachments/assets/25598ea6-cb36-42aa-8643-f370bf354ac7)

**Comment by JasonGUTU** [comment]
![66af7d6e4c746b24eb7aeaee](https://github.com/user-attachments/assets/723826b5-1e1f-4d57-9203-784ccff01abd)
 Check this out? The words that are too blur to identify can not be restore. It is because the limitation of input information.

**Comment by JasonGUTU** [comment]
Fidelity, Upscale 4

**Comment by Wangbk-dl** [comment]
> ![66af7d6e4c746b24eb7aeaee](https://private-user-images.githubusercontent.com/16154028/354903851-723826b5-1e1f-4d57-9203-784ccff01abd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3Nzc0MzksIm5iZiI6MTcyMjc3NzEzOSwicGF0aCI6Ii8xNjE1NDAyOC8zNTQ5MDM4NTEtNzIzODI2YjUtMWUxZi00ZDU3LTkyMDMtNzg0Y2NmZjAxYWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDEzMTIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNGIzMDFiNzI0ZmIwOWQ3ZmEzZmM0YTZmOTU4MGI1MTBiZmE5YzViNjNmMzA2NzRmYjMwNmEwNThlY2UzMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3_AD3Ei6rWHOiNCCmBO0GMyY0lEYye2F7VRa9TD4GfY) Check this out? The words that are too blur to identify can not be restore. It is because the limitation of input information.

Thanks for your reply and I've reproduced the result. 
Maybe for the blur text images, large upscale factor produces better results?

**Comment by JasonGUTU** [comment]
The current SUPIR is limited by the expressive power of VAE. So it may not be able to accurately restore very detailed textures. This is not a problem for most textures, but it is very serious for text. The processing of text requires additional steps to obtain a dedicated model. But for those texts that are already unrecognizable. I doubt that there is actually such a model that can create one from scratch.

**Comment by Wangbk-dl** [comment]
> The current SUPIR is limited by the expressive power of VAE. So it may not be able to accurately restore very detailed textures. This is not a problem for most textures, but it is very serious for text. The processing of text requires additional steps to obtain a dedicated model. But for those texts that are already unrecognizable. I doubt that there is actually such a model that can create one from scratch.

Thanks for the explanation.
