### ISSUE TITLE
What is the hardware requirements for testing? 

### ISSUE THREAD

**Issue by idhamari** [Fanghua-Yu/SUPIR#16]
The pre-trained model size is too large (239GB).  I understand that you used 64 Nvidia A6000 (48GB) Gpus for 10 days for the training. What are the hardware requirements for testing?

**Comment by xiaom233** [comment]
Thank you for your attention! 
VRAM： LLaVA~30G, SDXL~30G(output 1024*1024); RAM: 60G
It is a rough requirement on our device.

**Comment by aartikov** [comment]
@xiaom233 @Fanghua-Yu 
Could you please add the hardware requirements to the README?

**Comment by FurkanGozukara** [comment]
> ~SDXL~30G

this 30 GB VRAM is mandatory with LLaVA or without it? can't we quantize like 16bit 8bit 4bit?

**Comment by idhamari** [comment]
> @xiaom233 @Fanghua-Yu Could you please add the hardware requirements to the README?

This would be nice as not everyone has access to a GPU with 30GB of Memory. Is it possible to test using CPU assuming 32GB system memory?

**Comment by FurkanGozukara** [comment]
> > @xiaom233 @Fanghua-Yu Could you please add the hardware requirements to the README?
> 
> This would be nice as not everyone has access to a GPU with 30GB of Memory. Is it possible to test using CPU assuming 32GB system memory?

at the very least system should be able to runable on 24 gb gpus

i am pretty sure it is not optimized at all right now
