### ISSUE TITLE
Can this upscale high res .e.g 1024px images? I made it work on windows but got VRAM error and I wonder if worth to test on RunPod

### ISSUE THREAD

**Issue by FurkanGozukara** [Fanghua-Yu/SUPIR#25]
Even though terrible instructions and requirements I made it work on Windows :)

It was a challenge

Stage 1 works but at stage 2 I get out of VRAM error on 24 GB RTX 3090 - not using llava 

Now I can make it work on RunPod with A6000 GPU - 48 GB

but I want to upscale already high res images

e.g. 1024x1024 or 1536x1536

is it working? should I try?

**Comment by FurkanGozukara** [comment]
it works great

I released the auto installer will make a separate topic later hopefully

https://www.patreon.com/posts/99176057?pr=true

![camel_low](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/a12d7257-df7d-4237-b5fa-31fe0eabe7ef)


![camel_enhance](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/d3c53aa1-10a1-4ec2-9ed2-00625fa66938)

![family_photo_low](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/87c58c70-3879-4996-b53c-8f47ba952261)

![family_photo_enhance](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/ce802f9f-fcb0-43b5-9276-09c0f88e6465)

![SUPIR_interface](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/eb41aa80-9816-45bf-a076-dbc531ca329c)

**Comment by eriklgamedev** [comment]
You got it working on Windows? How much VRAM do you need?

**Comment by FurkanGozukara** [comment]
> You got it working on Windows? How much VRAM do you need?

yes but requires 30GB so I get out of VRAM error

CPU offloading is necessary but I don't plan to spend days for it :D

**Comment by i-amgeek** [comment]
@FurkanGozukara Were you using fp32 or fp16?

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara Were you using fp32 or fp16?

I used default settings and it shows fp16 for diffusion datatype and auto encoder datatype bf16

**Comment by Fanghua-Yu** [comment]
@FurkanGozukara Nice try!
Currently, you can run SUPIR on rtx 3090 with tiled VAE. As for A6000, it can generate at least 4096 * 4096 images.
However, we recommend an output resolution of 1024-2048px for better quality, as our training resolution is 1024px.
For upscaling tasks on already high res images, e.g. 4K, 8K, we are pushing tiled diffusion for better results now.

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara Nice try! Currently, you can run SUPIR on rtx 3090 with tiled VAE. As for A6000, it can generate at least 4096 * 4096 images. However, we recommend an output resolution of 1024-2048px for better quality, as our training resolution is 1024px. For upscaling tasks on already high res images, e.g. 4K, 8K, we are pushing tiled diffusion for better results now.

yes new updates are amazing and looking forward to new ones



can you give some info regarding the  encoder_tile_size=512, decoder_tile_size=64

What does bigger or lower do for each?

I also applied them to my scripts and i plan to add some new features hopefully : https://github.com/Fanghua-Yu/SUPIR/issues/38

**Comment by Harper714** [comment]
> @FurkanGozukara Nice try! Currently, you can run SUPIR on rtx 3090 with tiled VAE. As for A6000, it can generate at least 4096 * 4096 images. However, we recommend an output resolution of 1024-2048px for better quality, as our training resolution is 1024px. For upscaling tasks on already high res images, e.g. 4K, 8K, we are pushing tiled diffusion for better results now.

Hi, is the code with tiled diffusion available now?

**Comment by FurkanGozukara** [comment]
> > @FurkanGozukara Nice try! Currently, you can run SUPIR on rtx 3090 with tiled VAE. As for A6000, it can generate at least 4096 * 4096 images. However, we recommend an output resolution of 1024-2048px for better quality, as our training resolution is 1024px. For upscaling tasks on already high res images, e.g. 4K, 8K, we are pushing tiled diffusion for better results now.
> 
> Hi, is the code with tiled diffusion available now?

yes our APP works even with 12 GB gpus very well

hopefully we are going to publish 8bit loading so even lower VRAM and will work on kaggle. i am working on a kaggle notebook. free kaggle account

**Comment by yuanzhi-zhu** [comment]
> However, we recommend an output resolution of 1024-2048px for better quality, as our training resolution is 1024px.
@Fanghua-Yu What the actually training image size? You said "we crop images into 512×512 patches during training" in the paper
