### ISSUE TITLE
when   i   run test.py    on win? i have error about bf16 ,what should i do ?

### ISSUE THREAD

**Issue by zhanghongyong123456** [Fanghua-Yu/SUPIR#29]
i chage  SUPIR_v0.yaml:
ae_dtype: fp32
![image](https://github.com/Fanghua-Yu/SUPIR/assets/48466610/424ce689-4a16-4c3a-8b9c-22c2f151690c)
![image](https://github.com/Fanghua-Yu/SUPIR/assets/48466610/f2c712d1-da0a-4f41-9738-0675a0f96241)
![image](https://github.com/Fanghua-Yu/SUPIR/assets/48466610/e8de85d5-daa1-416a-8c61-de87b5ed9dda)

**Comment by wly-ai-bj** [comment]
In the file of test.py, the ae_dtype is refined by the argument of "--ae_dtype" again.

**Comment by zhanghongyong123456** [comment]
> In the file of test.py, the ae_dtype is refined by the argument of "--ae_dtype" again.
in  gradio_demo  have same  error，and  no argument   --ae_dtype
![image](https://github.com/Fanghua-Yu/SUPIR/assets/48466610/52bfd3c9-9e98-4fda-810b-c88a3576e2d6)

**Comment by zhanghongyong123456** [comment]
> In the file of test.py, the ae_dtype is refined by the argument of "--ae_dtype" again.

OK， I add  it
