### ISSUE TITLE
Full Tutorial + 1 Click 12 GB VRAM Installer + Batch Upscale + Comparison With Magnific - SUPIR Starts A New Era

### ISSUE THREAD

**Issue by FurkanGozukara** [Fanghua-Yu/SUPIR#38]
I have dedicated several days, working over 12 hours each day, on SUPIR (Scaling-UP Image Restoration), a cutting-edge image enhancement and upscaling model introduced in the paper [Scaling Up to Excellence: Practicing Model Scaling for Photo-Realistic Image Restoration In the Wild](https://arxiv.org/abs/2401.13627).

**This model is simply mind-blowing. At the bottom of this post, you will see side-by-side comparisons of SUPIR versus the extremely expensive online service, Magnific AI. Magnific is known to be the best among the community. However, SUPIR is by far superior. SUPIR also significantly outperforms Topaz AI upscale. SUPIR manages to remain faithful to the original image almost 100% while adding details and achieving super upscaling with the best realism.**

I made a full 33-minute tutorial, fully chaptered with manually written captions. The chapter's info is posted at the very bottom.

You can watch the video here: [SUPIR: New SOTA Open Source Image Upscaler & Enhancer Model Better Than Magnific & Topaz AI Tutorial](https://youtu.be/PqREA6-bC3w)

[**SUPIR: New SOTA Open Source Image Upscaler & Enhancer Model Better Than Magnific & Topaz AI Tutorial**](https://youtu.be/PqREA6-bC3w)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/QqzGQeKmOw7-aO7Ippqp2.png)](https://youtu.be/PqREA6-bC3w)

You can join our 6500+ member Discord for any help & discussion: [https://discord.com/servers/software-engineering-courses-secourses-772774097734074388](https://discord.com/servers/software-engineering-courses-secourses-772774097734074388)

Original repo of SUPIR: [https://github.com/Fanghua-Yu/SUPIR](https://github.com/Fanghua-Yu/SUPIR)

I have worked hard to make a [1-click installer](https://www.patreon.com/posts/supir-1-click-99176057) for Windows & RunPod. RunPod uses Linux, thus if you are a Linux user you can use RunPod files to install locally on Linux as well with a 1-click install.

Full instructions are shared in this post along with the scripts: [https://www.patreon.com/posts/supir-1-click-99176057](https://www.patreon.com/posts/supir-1-click-99176057)

Here are the installer files:

![image](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/584d06a0-aa93-4f4e-9a7b-58ef4aae1a34)

The installer works with Python 3.10.11. It generates a new pip venv and installs everything there. So you don't need Conda. Since it will generate its own VENV, it will not affect any other installations on your system.

The installer installs xFormers and Triton (we are using a pre-compiled wheel) and Pytorch 2.2.0 automatically for you on Windows and Linux.

The Gradio app launching interface is shown below:

![image](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/89b9cb7b-aeb6-4910-8263-cab2a490424d)

Currently, with the newest optimizations, the SUPIR app works great on RTX 3060 without LLaVA. I have tested it on my 12 GB single RTX 3060 GPU. So if you have a GPU that has 12GB or more VRAM, you can use it.

The installer downloads all models automatically as well. Also, I changed the base SDXL model with Juggernaut XL - V9 since it works better.

You can simply use any SDXL model. Instructions are on the Patreon post.

I also greatly improved the base Gradio APP. I made the interface more usable.

I added the number of images and randomized seed features. I made the image upscale scaler 0.1 precision.

Moreover, I have added a batch upscale feature as well.

You can see the improved advanced Gradio app interface below.

All the images the app generates will be automatically saved under the outputs folder. You can define the batch image processing outputs folder as well.

![image](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/0296bc4e-0329-42c6-a00f-6e95973796ab)

Here is the content of the Patreon post:

![image](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/e932a5ed-1c4d-4619-ba9a-3bccfd524593)

The chapters of the tutorial are as follows:

* 0:00 Introduction to SUPIR (Scaling-UP Image Restoration) full tutorial
* 2:10 How to download and install SUPIR on Windows or RunPod (thus Linux)
* 3:19 How to setup a community Pod on RunPod's newest interface 
* 4:33 How to install and start SUPIR on RunPod
* 7:10 How to use Proxy connect of RunPod
* 8:13 How to install and start our own quantization supporting LLaVA
* 9:22 Getting image description from our own LLaVA model
* 9:42 How to use SUPIR interface and testing camel image (test image 1) on SUPIR in details
* 12:07 Testing a very old family photo enhancement and upscaling with SUPIR (test image 2)
* 14:34 Where the generated images are saved
* 14:53 Testing the image of Arnold Schwarzenegger as a warrior (test image 3) on SUPIR in details
* 16:22 The effect of simple prompt vs detailed prompt
* 17:30 Testing a dragon statue enhancement and upscaling with SUPIR (test image 4)
* 17:42 How I used ChatGPT Plus / GPT-4 for image captioning
* 18:29 The model works with literally every resolution and example very big upscale
* 19:00 Testing image of a dinosaur in jurassic park image enhancement and upscaling with SUPIR (test image 5)
* 19:41 From 500px to 3000px upscale results and how to do very big upscale properly
* 22:39 GPU utilization of the SUPIR scripts
* 23:15 If you get out of VRAM error what can you do and how you can solve
* 25:22 Testing a MonsterMMORPG Game character (anime like drawing) upscaling and image enhancing (test image 6)
* 25:39 What to do if your image has transparent pixels to be able to upscale
* 27:35 Testing a black and white colored movie screenshot of a man image enhancement and upscaling with SUPIR (test image 7)
* 28:29 Testing a screenshot from the movie Predator enhancement and upscaling with SUPIR (test image 8)
* 29:12 The queue ability of the Gradio app of SUPIR
* 29:49 Testing an old photo of Muhammad Ali in a boxing stance image enhancement and upscaling with SUPIR (test image 9)
* 30:45 Testing a black and white colored movie screenshot of Charlie Chaplin image enhancement and upscaling with SUPIR (test image 10)

### Carefully look at the how much SUPIR can be loyal to the original image vs Magnific can be loyal to original image

![base_ali](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/d63157c1-dfdd-49f5-bae4-ac3c07be3118)

![magnific_ali](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/091fa260-e85e-4951-8cce-2395e32b7f93)

![supir_ali](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/00b1056a-03cc-4b3c-9465-417c7a3cc894)

![base_dino](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/875035b0-8f1e-4b79-8372-b2afe897a747)

![dino_magnific](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/852866ea-3dad-442c-893b-d10f4052740f)

![dino_supir](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/323bc182-e8f4-4013-b46a-dbe11f56500b)

![base_family](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/1b9512aa-f104-4a80-8dc7-fcd011bb44f7)

![magnific_family](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/d56deee1-4c88-4116-a35d-77f1c670eba1)

![supir_family](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/41a1e1f8-d226-47a3-a811-9ee798273f6b)

![base_camel](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/782d5071-eef6-468b-a56e-66e7c27ecb0d)

![magnific_camel](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/2ef37b38-a57d-46cc-a061-f2f0fe531ff5)

![supir_camel](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/9dbd7afe-6996-4137-8193-177410860278)

![base_vampire](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/a042cadb-2a86-45f5-a83a-84baf39f0f49)

![magnific_vampire](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/7cbd0ab9-838e-4eba-82c1-2b5011219685)

![supir_vampire](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/5762aa05-15e0-47f8-be60-845e610b7b4a)

![base_dragon](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/5c27a8d0-eb36-43c7-a3e5-f98ca8aa6185)

![magnific_dragon](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/cf595fb2-aa29-41e2-b720-b11669719529)

![supir_dragon](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/d5d58a42-fca1-440b-a8c7-f029de56d4b1)

![base_arnold](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/f3eff22e-3469-4596-bd2e-c0cb40a95055)

![magnific_arnold](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/86d767b8-fe9f-411d-9303-be3f92c0c237)

![supir_arnold](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/65c42c92-fbdb-4451-a088-47dbe671f7b8)

![base_predator](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/15883fdc-2d50-4bc9-9f89-150ce5f60f0f)

![magnific_predator](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/d78ea5f9-496c-4334-b8ed-6300467456a4)

![supir_predator](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/c07b7ab1-bd90-46f4-9621-f2074a4cd258)

![base_charlie](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/2ce9c9b4-c5ae-4465-8cac-ec963ed5b1c4)

![magnific_charlie](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/b6d3e3e8-233b-4447-9978-6d3e37e49f4d)

![supir_charlie](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/8959aabd-e027-4d6d-b008-908170e9c1c8)

![base_monster](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/c7f61cd0-950e-4880-b32a-d81e9a9953c9)

![magnific_monster](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/22db3a90-e593-41df-836f-d6646791340a)

![supir_monster](https://github.com/FurkanGozukara/Stable-Diffusion/assets/19240467/046139e6-d023-450c-97cd-72cc7a5ef905)

**Comment by zelenooki87** [comment]
You deserve ban for posting your "premium" sh**y stuff here. Everything can be done with following authors readme file.

**Comment by Revln9** [comment]
Can you please ban this guy ?

**Comment by JasonGUTU** [comment]
Hello and thanks for your work! You made a great video and your results are very important to us. Maybe someone else thinks it's inappropriate to post this as an issue. We can make it better and find you a better place to share your thoughts!

**Comment by FurkanGozukara** [comment]
> Hello and thanks for your work! You made a great video and your results are very important to us. Maybe someone else thinks it's inappropriate to post this as an issue. We can make it better and find you a better place to share your thoughts!

Thank you so much. I will hopefully make more people to know this Model. It is not getting the attention it deserves.

**Comment by Akarity** [comment]
I tried to install, based on the readme, but got a bunch of errors when installing requirements.

![2024-02-28 22_47_26-Anaconda Prompt](https://github.com/Fanghua-Yu/SUPIR/assets/80644899/743a3e2d-ec3d-47df-8186-9eca6404014d)

**Comment by FurkanGozukara** [comment]
@Akarity I made it installed via Python 3.10.11 venv. I really don't like Conda

**Comment by OoAnikioO** [comment]
> https://github.com/Fanghua-Yu/SUPIR
> 
> no paywall, one click installer

there is no one click installer of this page

**Comment by FurkanGozukara** [comment]
New updates added to our Gradio. I keep adding features requested by the supporters

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/ad52919d-7c3a-4301-a492-bb7d98d21126)

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/7e080f02-e40c-494f-8d22-d7ab9de37d12)

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/7e82fa25-5533-4cf8-b996-7e4ea7f9c4fb)

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/7ca70f8c-9895-4a86-a8a8-60f7b083204c)

**Comment by csatoshii** [comment]
people would have less of a problem with this he didn't put it behind a paywall. this isn't helping anyone but his own pockets.  Sure people need to make money, but it's done in such a sh*tty and spammy way - everywhere!

**Comment by FurkanGozukara** [comment]
Just updated to V19

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/a834536e-ad26-477e-ba63-77a3c3a2616e)

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/26b0fca2-8e02-424a-8e35-37fb8b764589)

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/2afcaac3-ca30-462c-9fe9-0d24465b0763)

**Comment by FurkanGozukara** [comment]
We updated to V21 and we got some SUPIR improvements

![new updates](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/7e225a10-c522-4222-af1b-7e4181d037b1)

![new options](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/74789981-da87-4e56-9285-9ef7e38d24f7)

![show off](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/d9409358-26df-473b-9a3c-326724dbb184)

![metadata](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/ab46da68-460d-4bff-a91c-5ad5add73c0f)

**Comment by FurkanGozukara** [comment]
We just made a new big update V22

Auto generate comparison video

https://github.com/Fanghua-Yu/SUPIR/assets/19240467/60b9f4e1-f968-4d26-8333-553739f7b8a5

![v22](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/ff985f66-e9e5-45b4-9660-8ec724b9a3ac)

**Comment by alcoartist** [comment]
GitHub policy isn't working here? Ban this patreon $$ "developer", please. He is spamming everywhere.

**Comment by PierrunoYT** [comment]
How can I use it inside Pinokio?

**Comment by FurkanGozukara** [comment]
We have been working non stop and added so many features

You can download and use from here standalone fully auto installer including download models  :
https://www.patreon.com/posts/supir-1-click-99176057

@PierrunoYT


https://github.com/Fanghua-Yu/SUPIR/assets/19240467/fa10341f-9f07-4d9c-8926-1f73ebe1bdaa

![new features](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/325356f3-404f-456e-9ae1-bc33d6cf5039)

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/371b4ce7-4983-44f4-b3e2-5fe6a6d425ca)

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/9b71cd0e-49cd-4eb3-b05b-b07a2a419c53)

**Comment by FurkanGozukara** [comment]
We are now version 41 : https://www.patreon.com/posts/99176057

Here look at all the features we brought

Displaying full status of upscale

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/bfb7c9c0-cc71-43b1-90fe-9274aa530c90)

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/77fc1a94-4ecf-4e65-81d1-57fcce5f36d4)

Auto make comparison video

https://github.com/Fanghua-Yu/SUPIR/assets/19240467/81787dd7-5f1a-4f6b-83f4-259d02726750

Look all the options and changelogs

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/e087d3dc-4e91-44cf-baba-74a63ad98fef)

We now have even process video input automatically

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/9de1198f-fbbe-4bf6-9841-cbbab7a29341)
