### ISSUE TITLE
Consider using the `ImageSlider` custom component for a sleeker demo

### ISSUE THREAD

**Issue by abidlabs** [Fanghua-Yu/SUPIR#4]
Hi folks! Great model and thanks for including the local Gradio demo. I'd suggest using the ImageSlider custom component: https://huggingface.co/spaces/pngwn/gradio_imageslider to make the demo even nicer.

**Comment by Fanghua-Yu** [comment]
Thanks! Since `ImageSlider` can only display single result, we added it as an optional choice.

**Comment by JasonGUTU** [comment]
Thanks for the suggestion!
