### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by al3dv2** [Fanghua-Yu/SUPIR#5]
Hi I have a error when I try to start the gradio, it's seems the problem from loading models do you guys have a better explanation of how install models ? thanks 
![ccd](https://github.com/Fanghua-Yu/SUPIR/assets/157552424/e734fba4-a838-47c6-95fe-b73efb39ac73)

**Comment by Fanghua-Yu** [comment]
Hello, pretrained model path should be defined in `CKPT_PTH.py` firstly, please refer to #23.
