### ISSUE TITLE
License conflict with Readme?

### ISSUE THREAD

**Issue by imperator-maximus** [Fanghua-Yu/SUPIR#51]
Hello,

the main license is MIT but at the end of the Readme there was this part added three days ago:

"The SUPIR ("Software") is made available for use, reproduction, and distribution strictly for non-commercial purposes. For the purposes of this declaration, "non-commercial" is defined as not primarily intended for or directed towards commercial advantage or monetary compensation."

In my opinion this stands in direct conflict with the MIT license.

**Comment by fakerybakery** [comment]
I concur. In addition, it says:

> This declaration does not in any way limit the rights under any open source license that may apply to the Software; it solely adds a condition that the Software shall not be used for commercial purposes.

However, this means that this code is no longer open-sourced, since NC doesn't comply with the OSD.

**Comment by Shadetail** [comment]
I would also like clarification on this.

**Comment by imperator-maximus** [comment]
@d8ahazard  are you a specialized lawyer on this topic?
If not nobody really knows. The original author could say that MIT was a mistake and it is non commercial. But I agree that would mean removing MIT license file as well. 
Best would be some official clarification from repo owners here.

Maybe original code until that commit is MIT and after that new commits are now. That would not make sense but who knows.

**Comment by fakerybakery** [comment]
> @Shadetail @fakerybakery @imperator-maximus
> 
> I'm not going to completely repeat myself, but if you read here #71 - the statement in the readme is pointless.
> 
> MIT means "Use it for whatever you want.". You can't change the license after it's been released.

You’re right about the permissiveness of the MIT license but if the author overrides it in the README it’s unclear which one applies. (IANAL). In fact, many AI projects on GitHub are MIT licensed but have this NC clause. I think the author’s intent is for it not to be used commercially

**Comment by d8ahazard** [comment]
> > @Shadetail @fakerybakery @imperator-maximus
> > I'm not going to completely repeat myself, but if you read here #71 - the statement in the readme is pointless.
> > MIT means "Use it for whatever you want.". You can't change the license after it's been released.
> 
> You’re right about the permissiveness of the MIT license but if the author overrides it in the README it’s unclear which one applies. (IANAL). In fact, many AI projects on GitHub are MIT licensed but have this NC clause. I think the author’s intent is for it not to be used commercially

It's pretty straightforward. The license wins. That's how it was originally released. 

While it is confusing, the license was first, and the terms of the MIT license are absolutely clear. 

@imperator-maximus - I am not a lawyer. But the the org I work for has them, and after consultation, that's the outcome. 

As I said, not trying to be nasty, I just want to help get this clarified for everybody involved...

**Comment by fakerybakery** [comment]
Even if the license was first, all modifications made after the NC clause was added are NC, no?

**Comment by d8ahazard** [comment]
> Even if the license was first, all modifications made after the NC clause was added are NC, no?

No, because the license is still MIT. Short of pulling the code and re-releasing it under a NC license, everything in *this* repository falls under the MIT license.

**Comment by d8ahazard** [comment]
It's like buying a piece of property that's zoned as commercial, and then putting up a sign in front that says "This is now a residentially zoned area." and expecting to not get in trouble for building condos on it. Or something like that.

**Comment by imperator-maximus** [comment]
I disagree here because the timeframe between the first release and the README was quite short (only a few days). It wasn't as if months had passed. In this case, choosing the MIT license might have been an oversight.
Take another example: if someone were to steal Windows' closed-source code and release it on GitHub under an MIT license, everyone would agree that it wouldn't actually be MIT-licensed code. It's important to consider the full context. I'm not sure of the relationship between the repository creator and the original authors of the paper. Perhaps the person intended to assist by contributing some code and uploading everything here, but didn't have complete permission to apply the MIT license.
In such a scenario—and this is purely speculative—you can't simply claim it's under the MIT license. Only the copyright owner has the authority to determine the licensing, and no one else.

**Comment by d8ahazard** [comment]
But it's not someone else's code. It's the author's original project. The *original* license for this *original* code we're discussing is MIT.

And the timeframe is irrelevant. The license on this project still says MIT. Intent, oversights, whatever don't have any bearing on the fact of what the license is.

I get your point. I get all of the points surrounding the ambiguity of this issue. And for those reasons, it's imperative that OP either release new code with a new license, which is likely a moot point by now - or remove the conflicting and irrelevant statement from the readme. 

But as it is now, there's not a ton of ground for anybody upset that it's being used commercially...

**Comment by d8ahazard** [comment]
LOL, so the solution is to just change the existing license?

Good thing the version I forked was released under MIT, hey?

**Comment by fakerybakery** [comment]
I think the NC still applies to forked code since it was in the readme before they switched to a dedicated NC license

**Comment by imperator-maximus** [comment]
but Readme had been changed after initial MIT release.

@d8ahazard has got some good points which I can fully understand and partially agree with but I also think that this is a difficult situation. So to be sure I recommend seeking legal advice from experts specializing in intellectual property law if you want to use this project (from first release version) in commercial context.

**Comment by JasonGUTU** [comment]
Thanks for your attention and point out the problem. Firstly, we are researchers. At the beginning of releasing this model, we did not realize the potential impact and issues it may have. Weeks after, we realize the value of SUPIR and the power it can have to help our future research. Because keep improve SUPIR can be hardly done with the resource in Universities. The legal experts are then involved weeks later and we have already done something. Thanks for raising this issue and we are learning to solve this problem.

We are not going to comment @d8ahazard 's theory and we are not going to delete this repo and relaunch it to cause inconvenience to those already star this repo. Thanks @imperator-maximus and @d8ahazard , and we are seeking legal advice on this issue.

We change the license already and we are happy that many companies respect our work and get touch with us for commercial collaboration. We are also happy to let them use SUPIR to evaluate its commercial value without any initial payment. We believe any business cooperation should be conducted on the basis of mutual respect. If you do not respect our work and try to find a gap in the roadblock, you may always do that. We are not Nintendo. But again, we think any cooperation should be conducted on the basis of mutual respect. If you respect our work, please put yourself in our shoes and think for us.

Finally, we are a group of researchers, we hope to further advance research and enable more people to benefit from technology like SUPIR. For this issue and related issues, we will close them. If you have any advise and problem, or want commercial collaboration on SUPIR, please email jinjin.gu@suppixel.ai. Thanks!

**Comment by mr-lab** [comment]
> we realize the value of SUPIR and the power it can have to help our future research. Because keep improve SUPIR can be hardly done with the resource in Universities. 

kinda understand ,but to us  SUPIR  won't help our future projects. the reason why SUPIR  is born is it uses SDXL model that was open and free , to say it clearly , you would never touch SDXL if it was using the same license as the one you are using . 
now think back on that , and imaging the many thing it could be built on top of  SUPIR  , that will never be built . 
to us SUPIR  was gonna upscale some MV depth maps using marigold Model ... not it won't 
Best of luck cheers.

**Comment by JasonGUTU** [comment]
> > we realize the value of SUPIR and the power it can have to help our future research. Because keep improve SUPIR can be hardly done with the resource in Universities.
> 
> kinda understand ,but to us SUPIR won't help our future projects. the reason why SUPIR is born is it uses SDXL model that was open and free , to say it clearly , you would never touch SDXL if it was using the same license as the one you are using . now think back on that , and imaging the many thing it could be built on top of SUPIR , that will never be built . to us SUPIR was gonna upscale some MV depth maps using marigold Model ... now it won't Best of luck cheers.

We understand your concerns. But the costs and risks of investing in Stability AI are also unbearable for us. The open source of SDXL is a great initiative, and we also hope to achieve similar things. But I believe you also know the current situation and dilemma of Stability AI. This is a difficult decision and we have to be more conservative and careful than ever. In fact, for companies seeking commercial licenses from us, we license them free of charge for a long time, and if the company does not make a profit using SUPIR, we will continue to maintain the free license. This defensive license is mainly set up to make our research and work sustainable.

**Comment by mr-lab** [comment]
> > > we realize the value of SUPIR and the power it can have to help our future research. Because keep improve SUPIR can be hardly done with the resource in Universities.
> > 
> > 
> > kinda understand ,but to us SUPIR won't help our future projects. the reason why SUPIR is born is it uses SDXL model that was open and free , to say it clearly , you would never touch SDXL if it was using the same license as the one you are using . now think back on that , and imaging the many thing it could be built on top of SUPIR , that will never be built . to us SUPIR was gonna upscale some MV depth maps using marigold Model ... now it won't Best of luck cheers.
> 
> We understand your concerns. But the costs and risks of investing in Stability AI are also unbearable for us. The open source of SDXL is a great initiative, and we also hope to achieve similar things. But I believe you also know the current situation and dilemma of Stability AI. This is a difficult decision and we have to be more conservative and careful than ever. In fact, for companies seeking commercial licenses from us, we license them free of charge for a long time, and if the company does not make a profit using SUPIR, we will continue to maintain the free license. This defensive license is mainly set up to make our research and work sustainable.

Well your concerns are really valid , hopefully one day AI companies start following Blender non-profit model 
again thank you.

**Comment by gexahedron** [comment]
Hi, sorry stupid question, I respect your license, no problem, I have a question though - is SUPIR based on SDXL, right? Should it be considered a derivative of SDXL? Should it also somehow respect the SDXL license then? Thanks.

**Comment by fakerybakery** [comment]
The SDXL license does not require derivatives to be licensed under the same license.
