### ISSUE TITLE
Severe Lack in How to Use Guide

### ISSUE THREAD

**Issue by rafstahelin** [Fanghua-Yu/SUPIR#52]
Would love some guide information for how to use all the deeper parameters in this awesome application

**Comment by eriklgamedev** [comment]
This might help:

--edm_steps: Number of steps for the EDM Sampling Scheduler. This determines how many iterations the sampling process will take. A higher number generally means more refinement but takes longer.

--s_stage1: Strength control for the first stage of processing. A negative value indicates that this stage is not used.

--s_churn: A hyperparameter of the EDM process, influencing the variability or diversity in the generated samples.

--s_noise: Another hyperparameter for EDM, affecting the amount of noise introduced during the diffusion process, which can impact the clarity or smoothness of the output.

--s_cfg: Classifier-free guidance scale for prompts. This parameter adjusts the influence of textual prompts on the generation process, affecting how closely the output matches the given textual description.

--s_stage2: Strength control for the second stage of processing. Adjusts the intensity of modifications in the second stage.

linear_CFG and --linear_s_stage2: These settings allow for a linear increase of the s_cfg and s_stage2 parameters from their start points (--spt_linear_CFG and --spt_linear_s_stage2) to their specified values through the process, providing a way to dynamically adjust the guidance strength.

--spt_linear_CFG and --spt_linear_s_stage2: Define the starting points for the linear increase of s_cfg and s_stage2, respectively.

--ae_dtype and --diff_dtype: Specify the data types (precision) used during inference for the autoencoder and diffusion processes, respectively, affecting memory usage and computational speed.

**Comment by barepixels** [comment]
a little confused about Param Setting and Model Selection.  If I choose Fidelity in Param Setting shouldn't Model Selection auto switch to v0F.ckpt?  Or is it 4 possible combination

Quality  in Param Setting + v0Q.ckpt
Quality  in Param Setting + v0F.ckpt
Fidelity  in Param Setting + v0Q.ckpt
Fidelity  in Param Setting + v0F.ckpt
