### ISSUE TITLE
Wierd color artifact of stage 1 model

### ISSUE THREAD

**Issue by man-sean** [Fanghua-Yu/SUPIR#53]
I have installed the repo following the README on a machine with an RTX8000 (49GB VRAM).
Stage one always returns distorted images, which is wrong, but I don't know what I am missing.

Example:
![image](https://github.com/Fanghua-Yu/SUPIR/assets/8748837/f2af6696-2767-4991-abdd-8bf6b02ec6bf)

Important notes:

1. I'm using `Model Selection = v0-Q` but v0-F return similar results
2. I'm using `Auto-Encoder Data Type = fp32` as RTX8000 does not support `bf16`
3. This behavior repeats also when using the test.py script, not just gradio
4. I run with `--no_llava` and provide the prompt manually, but this should not affect the stage 1

**Comment by Fanghua-Yu** [comment]
I have tested that `Auto-Encoder Data Type = fp32` and `--no_llava` work well in my service with RTX A6000.
It seems the parameters of VAE are not loaded correctly.

**Comment by man-sean** [comment]
> I have tested that `Auto-Encoder Data Type = fp32` and `--no_llava` work well in my service with RTX A6000.
> 
> It seems the parameters of VAE are not loaded correctly.

Thanks for the quick response!
Maybe I missed something in the loading process:
I left the SDXL checkpoint path as none (~) in the config. 
Should I do something else?

**Comment by Fanghua-Yu** [comment]
SDXL checkpoint should be this [SDXL base 1.0_0.9vae](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/sd_xl_base_1.0_0.9vae.safetensors). `SUPIR ckpt` do not contains parameters of the base UNet.

**Comment by man-sean** [comment]
> SDXL checkpoint should be this [SDXL base 1.0_0.9vae](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/sd_xl_base_1.0_0.9vae.safetensors). `SUPIR ckpt` do not contains parameters of the base UNet.

Thanks for the clarification. This is now working as expected 😃
