### ISSUE TITLE
How to use Stage1 and Stage2. Does stage1 get automatically get used when running before stage2?

### ISSUE THREAD

**Issue by rafstahelin** [Fanghua-Yu/SUPIR#54]
Just wondering if there is an automation. 

I assume stage1 output needs to be downloaded and reloaded into input in order to be used to enhance stage 2 effect when very low res. 

Can you confirm this?

**Comment by FurkanGozukara** [comment]
I just added this. but I don't get good results :) It applies Stage 1 and then Stage 2 on Stage 1 output

![updated interface](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/e0f304bc-f48c-4867-ada0-bc2fe18ce7f7)

**Comment by Fanghua-Yu** [comment]
> I just added this. but I don't get good results :) It applies Stage 1 and then Stage 2 on Stage 1 output
Hello, stage1 results is prepared for LLaVA, and is resized to 512. 
As there is already a denoising stage in stage 2, applying Stage 2 on Stage 1 Output leads to excessive information loss.

**Comment by FurkanGozukara** [comment]
> > I just added this. but I don't get good results :) It applies Stage 1 and then Stage 2 on Stage 1 output
> 
> Hello, stage1 results is prepared for LLaVA, and is resized to 512. As there is already a denoising stage in stage 2, applying Stage 2 on Stage 1 Output leads to excessive information loss.

thanks a lot for the explanation makes sense

**Comment by rafstahelin** [comment]
Ok that makes absolute sense: it's meant to speed up lava process. Thanks
