### ISSUE TITLE
create_SUPIR_model uses more than 29 GB RAM - Thus free Kaggle notebook not working

### ISSUE THREAD

**Issue by FurkanGozukara** [Fanghua-Yu/SUPIR#60]
Currently create_SUPIR_model inside util.py loads everything into RAM first with full precision

Thus it is using more than 29 GB RAM

I think model half param can be given to it as well

Or perhaps some other optimizations? 

I tried a lot but no success to reduce 30 GB initial RAM loading usage

**Comment by bishtybro** [comment]
30 gigs...that's way too much....there must be some bug or optimization issue...that dev's need to fix..

**Comment by cuiyufeng521** [comment]
i only have 16G*2,GG

**Comment by FurkanGozukara** [comment]
we fixed it

and now working even with 8bit and on 8gb gpus

our kaggle notebook also published

https://github.com/Fanghua-Yu/SUPIR/issues/94
