### ISSUE TITLE
"LLaVA is not available. Please add text manually."

### ISSUE THREAD

**Issue by Sumsar3** [Fanghua-Yu/SUPIR#66]
I'm trying to get LLaVA to work in SUPIR but I'm not able to do it. I downloaded the folders (143GB lol) and move it to the models folder:

![2024-03-06 195113](https://github.com/Fanghua-Yu/SUPIR/assets/50243267/baca8527-cfa6-4902-b535-1d518c29e75d)

Then I set the paths on CKPT_PTH.py:

![2024-03-06 195010](https://github.com/Fanghua-Yu/SUPIR/assets/50243267/879846cc-d83a-4bef-93a0-291269ef7f4f)

I run gradio with `python gradio_demo.py --use_tile_vae --use_image_slider --loading_half_params  --load_8bit_llava`

When I'm into gradio and I click on "LLaVA run" I get this error on Prompt Box:

![2024-03-06 195848](https://github.com/Fanghua-Yu/SUPIR/assets/50243267/d685eca7-bac1-411a-af82-c5ebb80f52b6)

No errors on cmd window.

What I'm doing wrong? Thanks.

**Comment by Fanghua-Yu** [comment]
This prompt is occurred when `use_llava = False`:
https://github.com/Fanghua-Yu/SUPIR/blob/bca9a727b8a756ddaad7f13401631b5fde9f7f66/gradio_demo.py#L75-L83
It should be true with your gradio setting. Try to find something wrong with this variant. (sync the repo first)

**Comment by Sumsar3** [comment]
Closing the issue since was a gradio problem. Thanks!
