### ISSUE TITLE
Licensing - The statement in your Readme is useless.

### ISSUE THREAD

**Issue by d8ahazard** [Fanghua-Yu/SUPIR#71]
So, I see this every now and again on Github, and I really want to (hopefully) help clarify something.

This project was released under the MIT license. It says so right here:

https://github.com/Fanghua-Yu/SUPIR#MIT-1-ov-file

And so...regardless of the "non-commercial" statement in the readme and the code...in all actuality, according to the MIT license, this project can 100% be used commercially, by anybody, at any time.

Not trying to be a jerk, but adding the statement to the license has about as much effect as posting something on Facebook saying that "Under the geneva convention, no federal or government agency shall access any content on my Facebook page.". That is...zero. The license, IMHO, is the holy grail. If you didn't want it used commercially, then it shouldn't have been released under the MIT license.

End of discussion. Not trying to be disrespectful, but the bit in the readme is 100% pointless other than to confuse people who may not know better. 

As such, I'd humbly suggest just removing it. Pandora's box has been opened...there's literally nothing that can be done about it now short of ceasing all development on this project, binning it, releasing a new one under the correct license, and hoping the internet stops working so nobody can ever get the original project or models ever again.

Or, just update the readme...

**Comment by JasonGUTU** [comment]
Please refer to [this issue](https://github.com/Fanghua-Yu/SUPIR/issues/51)

**Comment by mr-lab** [comment]
@d8ahazard the dude made a mistake . lets forget about it and respect his decision , I really was gonna add this to our project but license changed , it sucks really , unless he changes that on his own and let us expand on his work . there is nothing we can do until someone else comes with a better or similar project that is MIT .

**Comment by clover1980** [comment]
The example with Facebook is really bad (where everything regulated by TOS in fact, which user signing). Lawyer here. It really depends on jurisdiction in fact. In certain countries code are not protected by law incl any algorithms(companies using other ways like design & etc to protect their works), in USA it WAS protected until creation of such thing like "Ai" or machine generated code which is not protected, no authorship(worldwide courts position) and that Ai thing destroying all US copyright doctrine & corporate intellectual property (programmers implementing machine code in the core of commercial software) from inside.
As i remember originally non-commercial restrictions based on code somehow published from Meta by Stanford uni, original Llama, also some things published OpenAi and on this basis are made all modern tools and next new models (was that code made by humans or not is another story). After that mostly everything Ai-related which openly released is for research only use, not from commercialization but mostly as safeguard from serious financial damages made by these tools to third-party (there's a many dangers like that case in S-Korea by liveportrait which made bank clerk to make a huge monetary mistake). The topic of datasets and shady legality of such is another different story. 
Commercial license gives you nothing here, in all Ai industry the only product which can be sold is only tools and nothing more - any produce by Ai tools not protected worldwide (even if there will be some country which makes different-existence of only one without recognition rights enough to destroy value worldwide) and can be copied by anyone legally (please don't make commercial logos with Ai, do not buy any Ai art-music-etc, you're not obtaining any property, sellers of such which hiding that buyer obtaining nothing-non-human works can be easily sued in any court).
