### ISSUE TITLE
multiple versions of gradio

### ISSUE THREAD

**Issue by shaobeichen** [Fanghua-Yu/SUPIR#83]
INFO: pip is looking at multiple versions of gradio to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 1) and -r requirements.txt (line 2) because these package versions have conflicting dependencies.

The conflict is caused by:
    fastapi 0.95.1 depends on pydantic!=1.7, !=1.7.1, !=1.7.2, !=1.7.3, !=1.8, !=1.8.1, <2.0.0 and >=1.6.2
    gradio 4.16.0 depends on pydantic>=2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by shaobeichen** [comment]
but run gradio_demo.py appearing

  File "gradio_demo.py", line 4, in <module>
    from gradio_imageslider import ImageSlider
  File "/usr/local/envs/SUPIR/lib/python3.8/site-packages/gradio_imageslider/__init__.py", line 1, in <module>
    from .imageslider import ImageSlider
  File "/usr/local/envs/SUPIR/lib/python3.8/site-packages/gradio_imageslider/imageslider.py", line 16, in <module>
    from gradio.events import Events
ImportError: cannot import name 'Events' from 'gradio.events' (/usr/local/envs/SUPIR/lib/python3.8/site-packages/gradio/events.py)

**Comment by shaobeichen** [comment]
I try upgrad fastapi to 0.110.0, but triton need upgrad to 2.2.0

The conflict is caused by:
    The user requested triton==2.1.0
    torch 2.2.1 depends on triton==2.2.0; platform_system == "Linux" and platform_machine == "x86_64" and python_version < "3.12"
    The user requested triton==2.1.0
    torch 2.2.0 depends on triton==2.2.0; platform_system == "Linux" and platform_machine == "x86_64"

then pydantic version need adjust , I'm tired

**Comment by S0ulan** [comment]
Same shit for me its annyoing

**Comment by FurkanGozukara** [comment]
well it is really hard to make it run. i have been working on it for weeks : https://github.com/Fanghua-Yu/SUPIR/issues/38

our app works 1 click install for Windows & Linux (RunPod) with 12 GB GPUs including auto caption

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/d7b39a13-cf7c-4ee3-8510-013fd4ab20b4)
