### ISSUE TITLE
how tu run?

### ISSUE THREAD

**Issue by ifredom** [Fanghua-Yu/SUPIR#84]
windows 10
conda:  python 3.10.11
gpu: 3060 12G

It took me a whole day to install it, and when I ran using the instructions given in the documentation, there were a lot of errors. What should I do?

`python gradio_demo.py --ip 0.0.0.0 --port 6688 --use_image_slider --log_history --loading_half_params --use_tile_vae --load_8bit_llava
`
![image](https://github.com/Fanghua-Yu/SUPIR/assets/13759936/8eab3c57-4696-4b95-94fb-902ec20db750)

**Comment by FurkanGozukara** [comment]
well it is really hard to make it run. i have been working on it for weeks : https://github.com/Fanghua-Yu/SUPIR/issues/38

our app works 1 click install with 12 GB GPUs including auto caption

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/d7b39a13-cf7c-4ee3-8510-013fd4ab20b4)
