### ISSUE TITLE
I have deployed the dual-card A6000 model. If you have any related questions, you can ask #85.

### ISSUE THREAD

**Issue by yikexiaoxing** [Fanghua-Yu/SUPIR#85]

**Comment by ocean1229-max** [comment]
Hello, I would like to ask if you can ask some basic questions about operation? I had some problems when running the code given by the author on Colab. I would like to ask how the code in the "Usage of SUPIR" section runs? I always get errors here, can you show me your running code? Thank you very much!
![Mis1](https://github.com/Fanghua-Yu/SUPIR/assets/103340883/c484a183-19ec-4164-9035-9b85177db487)

![Mis2](https://github.com/Fanghua-Yu/SUPIR/assets/103340883/ec97c6ac-c8f1-484c-9925-f11f9eed5e3f)

**Comment by yikexiaoxing** [comment]
第一个问题看起来好像是没有把所需的模型 放置在指定文件夹内，重新检查一下模型地址。第二个问题，你不应该这样运行，这一部分是作者用来解释代码参数的，如果要是运行，尝试下面两种方式，一种是使用python脚本，你需要提供要处理图片的文件夹，输出的文件夹。另一种是gradio创建的Web界面，可以在前端上传图片，进行交互式处理。希望我的回答对你有帮助！

**Comment by Oceanshy12-YANG** [comment]
首先十分感谢您的帮助！
第一个问题， 我想问一下指定的文件夹意思是放置在CKPT_PTH.py里面是吗(如图  0所示)? 我把模型放在了Google drive里面，要是提供了正确的地址，以下这两行代码就可以正常运行是么？
* [CKPT_PTH.py] --> LLAVA_CLIP_PATH, LLAVA_MODEL_PATH, SDXL_CLIP1_PATH, SDXL_CLIP2_CACHE_DIR 
* [options/SUPIR_v0.yaml] --> SDXL_CKPT, SUPIR_CKPT_Q, SUPIR_CKPT_F
第二个问题，实在抱歉，我在DiffBIR的stage1里面看过类似的运行方式（如图 1所示），导致我以为这是运行的代码。我的本意是只要跑通就可以，因为上次使用gradio的时候总是出现问题，按照您给我的第一种方法，我可能需要自己创建一个.py文件来运行，这对我来说可能超前了。我在reddit网站上查看了，如果按照您说的第二种方法使用gradio的话，我在最后需要运行“python gradio_demo.py --use_tile_vae --no_llava --use_image_slider --loading_half_params”应该就可以跑通了。
由于是最近才开始了解如何运行模型，可能会询问一些比较粗浅的问题，所以给您带来了麻烦，再次对您给我提供的帮助感激不尽！
![图 0](https://github.com/Fanghua-Yu/SUPIR/assets/152771172/3c6c9241-6279-47cf-a6a5-7b383bda1bf1)
![图 1](https://github.com/Fanghua-Yu/SUPIR/assets/152771172/22f76b49-d816-4ade-94f3-040d4cb442d3)

**Comment by yikexiaoxing** [comment]
好的，如果你想尝试运行代码，可以参考https://openbayes.com/console/public/tutorials/kpQAHQLpSrh，我已经将所需的文件整理好，只需简单运行即可

**Comment by FurkanGozukara** [comment]
it is really hard to make SUPIR work based on this repo alone

we worked few weeks

if you be interested in check this out as well : https://github.com/Fanghua-Yu/SUPIR/issues/38

**Comment by Oceanshy12-YANG** [comment]
> 好的，如果你想尝试运行代码，我已经将所需的文件整理好，只需简单运行即可可以参考https://openbayes.com/console/public/tutorials/kpQAHQLpSrh

十分感谢！我成功的在这个上面运行了！哈哈哈哈您实在是太强大了！谢谢！

**Comment by firehua01** [comment]
![微信图片_20240411085534](https://github.com/Fanghua-Yu/SUPIR/assets/166671340/c72bae16-b630-4347-9dd7-09c2586a9378)
我想请问一下，为什么我之前用的好好的，今天再用显示oom了，显卡是A40

**Comment by Oceanshy12-YANG** [comment]
> ![微信图片_20240411085534](https://private-user-images.githubusercontent.com/166671340/321442230-c72bae16-b630-4347-9dd7-09c2586a9378.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTAzNjYsIm5iZiI6MTcxMzE1MDA2NiwicGF0aCI6Ii8xNjY2NzEzNDAvMzIxNDQyMjMwLWM3MmJhZTE2LWI2MzAtNDM0Ny05ZGQ3LTA5YzI1ODZhOTM3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwMzAxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2Q0NGI3OTgyMmE1MmEyMjc3NTBlNzgyYjEyMDExOWVhZWZlZGYxZTY2YjRkZjI0YWYxYTM4OTAwZjVjYzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UcVg54g18n9SpuR6azIYq2i1DygVeNxfF67v_uLYIlI) 我想请问一下，为什么我之前用的好好的，今天再用显示oom了，显卡是A40

兄弟，你的问题解决了吗？请问是什么原因导致的？

**Comment by Oceanshy12-YANG** [comment]
> ![微信图片_20240411085534](https://private-user-images.githubusercontent.com/166671340/321442230-c72bae16-b630-4347-9dd7-09c2586a9378.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTAzNjYsIm5iZiI6MTcxMzE1MDA2NiwicGF0aCI6Ii8xNjY2NzEzNDAvMzIxNDQyMjMwLWM3MmJhZTE2LWI2MzAtNDM0Ny05ZGQ3LTA5YzI1ODZhOTM3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwMzAxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2Q0NGI3OTgyMmE1MmEyMjc3NTBlNzgyYjEyMDExOWVhZWZlZGYxZTY2YjRkZjI0YWYxYTM4OTAwZjVjYzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UcVg54g18n9SpuR6azIYq2i1DygVeNxfF67v_uLYIlI) 我想请问一下，为什么我之前用的好好的，今天再用显示oom了，显卡是A40

兄弟，你的问题解决了吗？
