### ISSUE TITLE
An exception occurred: stat: path should be string, bytes, os.PathLike or integer

### ISSUE THREAD

**Issue by Blackstylez83** [Fanghua-Yu/SUPIR#88]
Hai, is anyone could help why this error show up ? i dont know what im doing wrong, when it launch i just use default setting and try upload image and process single, but  this error show up. Any advice ? many thanks 

![image](https://github.com/Fanghua-Yu/SUPIR/assets/136671589/c0dd5390-b3c9-4689-a1a0-faf458910103)

**Comment by FurkanGozukara** [comment]
hello where did you obtain it? if you are our patreon supporter please message me from there and hopefully i will help you to fix your issue : https://www.patreon.com/posts/99176057

if you are not we don't allow it to be used

**Comment by Blackstylez83** [comment]
> hello where did you obtain it? if you are our patreon supporter please message me from there and hopefully i will help you to fix your issue : https://www.patreon.com/posts/99176057
> 
> if you are not we don't allow it to be used

Yes finally yesterday im notice thats from patreon workflow, someone share it on facebook, thats why i already closed my issue, i already delete all installation.

**Comment by FurkanGozukara** [comment]
> > hello where did you obtain it? if you are our patreon supporter please message me from there and hopefully i will help you to fix your issue : https://www.patreon.com/posts/99176057
> > if you are not we don't allow it to be used
> 
> Yes finally yesterday im notice thats from patreon workflow, someone share it on facebook, thats why i already closed my issue, i already delete all installation.

can you point me from which facebook? ty

**Comment by Blackstylez83** [comment]
I subs so many grup AI on facebook and forgot which one i download from, but you can try search on facebook  "Supir One click"

**Comment by FurkanGozukara** [comment]
> I subs so many grup AI on facebook and forgot which one i download from, but you can try search on facebook "Supir One click"

thanks i found and shared another post in that group

**Comment by Blackstylez83** [comment]
Yes ive seen your post in SD korea hehe - btw sorry didnt mean to install it illegally .

**Comment by FurkanGozukara** [comment]
> Yes ive seen your post in SD korea hehe - btw sorry didnt mean to install it illegally .

ye South Korea is not a poor country 5$ is nothing for them :)
