### ISSUE TITLE
Any workflows for ComfyUI

### ISSUE THREAD

**Issue by fememystic** [Fanghua-Yu/SUPIR#90]
Can't find workflows for Comfy on your page, could you give some good,  please?

**Comment by FurkanGozukara** [comment]
i know this : https://github.com/kijai/ComfyUI-SUPIR

also check this out easier to use : https://github.com/Fanghua-Yu/SUPIR/issues/38

**Comment by fememystic** [comment]
Thank you! i love the supir forst version node, it's so eazy to use and i like the result, is the 2nd version that good to stop using first one?
