### ISSUE TITLE
8GB VRAM support came to enhanced SUPIR with 8bit model loading, so many great features, totally 1 click install, runs on FP16 GPUs and also a free Kaggle notebook

### ISSUE THREAD

**Issue by FurkanGozukara** [Fanghua-Yu/SUPIR#94]
We have been relentlessly working on our [SUPIR APP (now V44) ](https://www.patreon.com/posts/99176057) development for weeks now and full time. If you have any questions please reply

I know you have been waiting all these features from the SUPIR developers but they are a researcher team funded to do research not develop apps

So with your support I did spent huge time to develop

You can download all scripts from : https://www.patreon.com/posts/99176057

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/dfa18f5d-f54b-4166-88e4-ea5b604a96ff)

So what improvements we have?

Working on FP16 older GPUs such as RTX 1080
A free Kaggle notebook for people who doesn't have a strong GPU - Kaggle provides dual T4 GPU 30 hours every week for free
Amazing image saving naming system
Total batch processing system including auto captioning and captions are saved
Extremely VRAM optimized
Displaying all of the status and progress messages during the upscale
SDXL Lightning models support with 10 steps high quality
Give any folder path as models folder path and on the fly change any model you want
FP8 support that makes our SUPIR works on 8GB VRAM GPUs amazingly fast
So if you have a GPU with 8GB or better you can use our SUPIR app
Integrated 4-bit, 8bit or 16bit LLaVA
Automatic LLaVA unloading if you are limited on VRAM
Automatic moving models to CPU therefore you can use both LLaVA and upscaling on lower end GPUs and almost no speed loss
1 Click to install on Windows, Linux, RunPod with necessary files and instructions
Fully coded image metadata system
With our FP8 model loading, you can upscale into very high resolutions even on low end GPUs
Supports taking input video and video upscaling - still need some improvements and fixes but all frames are properly upscaled
Supports custom prompt for face restore

Here a quick demo video of the app and hopefully full new updated tutorial coming to : https://www.youtube.com/SECourses

https://github.com/Fanghua-Yu/SUPIR/assets/19240467/c4aa17c6-ceb7-49a7-9d72-1be5a447d130

SUPIR is the very best AI image upscaler at the moment with respected to staying loyal to the original image

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/31c7f3c8-5799-46c9-bb89-67d05532b9d4)

All supported command line arguments

```
--ip: IP address for the server to listen on.
--share: Set to True to share the app publicly.
--port: Port number for the server to listen on.
--log_history: Enable logging of request history.
--loading_half_params: Enable loading model parameters in half precision to reduce memory usage.
--fp8: Enable loading model parameters in FP8 precision to reduce memory usage.
--autotune: Automatically set precision parameters based on the amount of VRAM available.
--fast_load_sd: Enable fast loading of model state dict and prevents unnecessary memory allocation. But may uses more VRAM.
--use_tile_vae: Enable tiling for the VAE to handle larger images with limited memory.
--outputs_folder_button: Outputs Folder Button Will Be Enabled.
--use_fast_tile: Use a faster tile encoding/decoding, may impact quality.
--encoder_tile_size: Tile size for the encoder. Larger sizes may improve quality but require more memory.
--decoder_tile_size: Tile size for the decoder. Larger sizes may improve quality but require more memory.
--load_8bit_llava: Load the LLAMA model in 8-bit precision to save memory.
--load_4bit_llava: Load the LLAMA model in 4-bit precision to significantly reduce memory usage.
--ckpt: Path to the checkpoint file for the model.
--ckpt_browser: Enable a checkpoint selection dropdown.
--ckpt_dir: Directory where model checkpoints (e.g. SDXL 1.0 base) are stored.
--theme: Theme for the UI. Use 'default' or specify a custom theme.
--open_browser: Automatically open the web browser when the server starts.
--outputs_folder: Folder where output files will be saved.
--debug: Enable debug mode, disables open_browser, and adds ui buttons for testing elements.
--dont_move_cpu: Disables moving models to the CPU after completed. If you have sufficient VRAM enable this.
```

![image](https://github.com/Fanghua-Yu/SUPIR/assets/19240467/0e6d491a-ccbe-4dd8-9421-ea9d12845374)

**Comment by Archit01** [comment]
Why is it paid ?
